language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install -r test-requirements.txt --use-mirrors
    - pip install --use-mirrors unittest2
    - python setup.py develop
script: unit2 discover -v && flake8 circus
notifications:
    email: tarek@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change
