language: python
python:
- "2.6"
- "2.7"
script: python setup.py test
notifications:
  email: 
    - tarek@mozilla.com
    - alexis@mozilla.com
  irc:
    channels: 
        - "irc.freenode.org#mozilla-circus"
    on_success: change
